music/urls.py
from django.contrib import admin
from django.urls import path, include
from recommender import views
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='recommender/')),
    path('recommender/', include('recommender.urls')),
    path('social/', include('social_django.urls')),
    path('accounts/profile/', views.post_sign_in, name='post_sign_in'),
]

recommender/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'recommender'

urlpatterns = [
    path('', views.get_home, name='get_home'),
    path('home/', views.get_home, name='get_home'),
    path('explore/', views.get_explore, name='get_explore'),

    path('signin/', views.get_signin, name='get_signin'),
    path('registration/', views.get_registration, name='get_registration'),
    path('logout/',views.logout_view,name="logout_view"),
    path('logout_view/', views.logout_view, name='logout_view'),

    path('profile/<str:user_name>', views.get_profile, name='get_profile'),

    path('myprofile/', views.get_myprofile,name='get_myprofile'),
    path('myprofile/profile_pic/', views.update_profile_picture, name='update_profile_picture'),
    path('myprofile/edit_bio/', views.update_bio, name='edit_bio'),
    path('myprofile/update_bio/', views.update_bio, name='update_bio'),
    path('myprofile/settings/',views.get_settings,name="get_settings"),
    path('myprofile/update_settings/',views.update_settings,name="update_settings"),
    path('myprofile/password/', views.change_password, name="change_password"),
    
    path('history/', views.get_history, name='get_history'),

    path('artist/', views.get_artist, name='get_artist'),
    path('album/', views.get_album, name='get_album'),
    path('track/', views.get_track, name='get_track'),
    path('user/', views.get_user, name='get_user'),
    
    path('playlist/', views.get_playlists, name='get_playlists'),
    path('playlist/<int:playlist_num>/', views.playlist_view, name='playlist_view'),
    path('playlist/<str:user_name>/', views.get_user_playlists, name='get_user_playlists'),
    path('playlist/create/<str:user_name>/', views.create_playlist, name='create_playlist'),
    path('playlist/<int:playlist_num>/add_song_update', views.add_song_update, name='add_song_update'),
    path('playlist/<int:playlist_num>/add_song_update/<str:song_id>', views.playlist_append, name="playlist_append"),
    path('playlist/<int:playlist_num>/remove_song_update/<str:song_id>', views.remove_song, name="remove_song"),

    path('following/<str:user_name>', views.get_following, name='get_following'),
    path('follow/<str:friend_name>', views.following_list_append, name='add_friend'),
    path('unfollow/<str:friend_name>', views.following_list_remove, name='remove_friend'),
    path('followers/<str:user_name>', views.get_followers, name='get_followers'),

    path('dislikes/', views.get_dislikes, name= 'get_dislikes'),
    path('dislikes/<str:user_name>', views.get_dislikes, name= 'get_dislikes'),
    path('dislike/song/<str:user_name>/<str:track_id>', views.dislike_song, name='dislike_song'),
    path('undislike/song/<str:user_name>/<str:track_id>/', views.undislike_song, name='undislike_song'),
    path('dislike/album/<str:user_name>/<str:album_id>', views.dislike_album, name='dislike_album'),
    path('undislike/album/<str:user_name>/<str:album_id>/', views.undislike_album, name='undislike_album'),
    path('dislike/artist/<str:user_name>/<str:artist_id>', views.dislike_artist, name='dislike_artist'),
    path('undislike/artist/<str:user_name>/<str:artist_id>/', views.undislike_artist, name='undislike_artist'),
    path('dislike/playlist/<str:user_name>/<str:playlist_id>', views.dislike_playlist, name='dislike_playlist'),
    path('undislike/playlist/<str:user_name>/<str:playlist_id>/', views.undislike_playlist, name='undislike_playlist'),
    
    path('album/<str:album_id>/', views.view_album, name="view_album"),
    path('artist/<str:artist_name>/', views.view_artist, name="view_artist"),
]
 

recommender/views.py
import random
from pickle import GET
from .models import *
from .forms import RegisterForm, SigninForm, UpdateSettingsForm, UpdatePasswordForm, SearchForm, PlaylistForm, ProfilePictureForm, BioForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect
from collections import Counter


def get_home(request):
    MAX_LENGTH = 3
    dislikes = Dislikes.objects.all()

    getDislikedSongs = dislikes.values_list('tracks', flat=True)
    dislikedSongs = []
    songCount = Counter(getDislikedSongs)
    topSongs = songCount.most_common(3)
    for song in topSongs:
        if song and len(dislikedSongs) < MAX_LENGTH:
            if song not in dislikedSongs:
                dislikedSongs.append(Musicdata.objects.get(id=song[0]))
                
    getDislikedAlbums = dislikes.values_list('albums', flat=True)
    dislikedAlbums = []
    albumCount = Counter(getDislikedAlbums)
    topAlbums = albumCount.most_common(3)
    for album in topAlbums:
        if album and len(dislikedAlbums) < MAX_LENGTH:
            if album not in dislikedAlbums:
                dislikedAlbums.append(Album.objects.get(album_id=album[0]))


    getDislikedPlaylists = dislikes.values_list('playlists', flat=True)
    dislikedPlaylists = []
    playlistCount = Counter(getDislikedPlaylists)
    topPlaylists = playlistCount.most_common(3)
    for playlist in topPlaylists:
        if playlist and len(dislikedPlaylists) < MAX_LENGTH:
            if playlist not in dislikedPlaylists:
                dislikedPlaylists.append(
                    Playlist.objects.get(playlist_id=str(int(playlist[0])-1)))

    if request.user.is_authenticated:

        owner = User.objects.get(username=request.user.username)
        userPlaylists = Playlist.objects.filter(playlist_owner=owner)
        Userdislikes = Dislikes.objects.filter(user=owner)

        getDislikedSongs = Userdislikes.values_list('tracks', flat=True)
        UserdislikedSongs = []
        for track in getDislikedSongs:
            if track:
                UserdislikedSongs.append(Musicdata.objects.get(id=track))

        getDislikedAlbums = Userdislikes.values_list('albums', flat=True)
        UserdislikedAlbums = []
        for album in getDislikedAlbums:
            if album:
                UserdislikedAlbums.append(Album.objects.get(album_id=album))

        getDislikedPlaylists = Userdislikes.values_list('playlists', flat=True)
        UserdislikedPlaylists = []
        for p in getDislikedPlaylists:
            if p:
                UserdislikedPlaylists.append(
                    Playlist.objects.get(playlist_id=str(int(p)-1)))
    else:  
        userPlaylists = []
        UserdislikedSongs = []
        UserdislikedAlbums = []
        UserdislikedPlaylists = []

    args = {
        'playlists': userPlaylists,
        'TopdislikedSongs': dislikedSongs,
        'TopdislikedAlbums': dislikedAlbums,
        'TopdislikedPlaylists': dislikedPlaylists,
        'dislikedSongs': UserdislikedSongs,
        'dislikedAlbums': UserdislikedAlbums,
        'dislikedPlaylists': UserdislikedPlaylists,
    }

    return render(request, "recommender/home.html", args)


def get_explore(request):
    songs = Musicdata.objects.all()
    sResp = list(songs)
    random.shuffle(sResp)
    albums = Album.objects.all()
    alResp = list(albums)
    random.shuffle(alResp)
    playlists = Playlist.objects.all()
    pResp = list(playlists)
    random.shuffle(pResp)
    artists = Artist.objects.all()
    arResp = list(artists)
    random.shuffle(arResp)
    userResp = User.objects.all()
    uResp = list(userResp)
    random.shuffle(uResp)

    if request.user.is_authenticated:

        following = FriendsList.objects.filter(user=request.user).values_list('friends')
        followingList = []
        for f in following:
            followingList.append(User.objects.get(id=f[0]))

        owner = User.objects.get(username=request.user.username)
        userPlaylists = Playlist.objects.filter(playlist_owner=owner)
        dislikes = Dislikes.objects.filter(user=owner)

        getDislikedSongs = dislikes.values_list('tracks', flat=True)
        dislikedSongs = []
        for track in getDislikedSongs:
            if track:
                dislikedSongs.append(Musicdata.objects.get(id=track))

        getDislikedArtists = dislikes.values_list('artists', flat=True)
        dislikedArtists = []
        for artist in getDislikedArtists:
            if artist:
                dislikedArtists.append(Artist.objects.get(artist_id=artist))

        getDislikedAlbums = dislikes.values_list('albums', flat=True)
        dislikedAlbums = []
        for album in getDislikedAlbums:
            if album:
                dislikedAlbums.append(Album.objects.get(album_id=album))

        getDislikedPlaylists = dislikes.values_list('playlists', flat=True)
        dislikedPlaylists = []
        for p in getDislikedPlaylists:
            if p:
                dislikedPlaylists.append(
                    Playlist.objects.get(playlist_id=str(int(p)-1)))

        friends = FriendsList.objects.filter(user=request.user).values_list('friends')
        friendsList = list(friends)
        friendsDislikeSongList = []
        friendsDislikeAlbumList = []
        friendsDislikePlaylistList = []
        if friendsList:
            for friend in friendsList:
                friendsDislikes = Dislikes.objects.filter(user=friend)
                getFriendsDislikedSongs = friendsDislikes.values_list('tracks',flat=True)
                getFriendsDislikedAlbums = friendsDislikes.values_list('albums',flat=True)
                getFriendsDislikedPlaylists = friendsDislikes.values_list('playlists',flat=True)
                for track in getFriendsDislikedSongs:
                    if track:
                        friendsDislikeSongList.append(Musicdata.objects.get(id=track))
                for album in getFriendsDislikedAlbums:
                    if album:
                        friendsDislikeAlbumList.append(Album.objects.get(album_id=album))
                for playlist in getFriendsDislikedPlaylists:
                    if playlist:
                        friendsDislikePlaylistList.append(Playlist.objects.get(playlist_id=str(int(playlist) - 1)))

            friendsDislikeSongList = friendsDislikeSongList[:3]
            friendsDislikeAlbumList = friendsDislikeAlbumList[:3]
            friendsDislikePlaylistList = friendsDislikePlaylistList[:3]

            if len(friendsDislikeSongList) < 3:
                for _ in range(3 - len(friendsDislikeSongList)):
                    while True:
                        currSong = random.choice(list(Musicdata.objects.all()))
                        if currSong not in friendsDislikeSongList:
                            friendsDislikeSongList.append(currSong)
                            break

            if len(friendsDislikeAlbumList) < 3:
                for _ in range(3 - len(friendsDislikeAlbumList)):
                    while True:
                        currAlbum = random.choice(list(Album.objects.all()))
                        if currAlbum not in friendsDislikeAlbumList:
                            friendsDislikeAlbumList.append(currAlbum)
                            break
                    
            if len(friendsDislikePlaylistList) < 3:
                for _ in range(3 - len(friendsDislikePlaylistList)):
                    while True:
                        currPlaylist = random.choice(list(Playlist.objects.all()))
                        if currPlaylist not in friendsDislikePlaylistList:
                            friendsDislikePlaylistList.append(currPlaylist)
                            break

            random.shuffle(friendsDislikeSongList)
            random.shuffle(friendsDislikeAlbumList)
            random.shuffle(friendsDislikePlaylistList)

    else:
        userPlaylists = []
        dislikedSongs = []
        dislikedAlbums = []
        dislikedArtists = []
        dislikedPlaylists = []
        friendsDislikeSongList = []
        friendsDislikeAlbumList = []
        friendsDislikePlaylistList = []
        followingList = []

    args = {
        'songs': sResp[:3],
        'albums': alResp[:3],
        'recPlaylists': pResp[:3],
        'artists': arResp[:3],
        'users': uResp[:10],
        'playlists': userPlaylists,
        'dislikedSongs': dislikedSongs,
        'dislikedAlbums': dislikedAlbums,
        'dislikedArtists': dislikedArtists,
        'dislikedPlaylists': dislikedPlaylists,
        'friendsDislikeSongList': friendsDislikeSongList,
        'friendsDislikeAlbumList': friendsDislikeAlbumList,
        'friendsDislikePlaylistList': friendsDislikePlaylistList,
        'following': followingList,
    }
    return render(request, "recommender/explore.html", args)


def find_albums(artist, from_year=None, to_year=None):
    query = Musicdata.objects.filter(track_artist__contains=artist)
    if from_year is not None:
        query = query.filter(track_album_release_date__gte=from_year)
    if to_year is not None:
        query = query.filter(track_album_release_date__lte=to_year)
    # return list(query.order_by('-track_popularity').values('track_id'))
    return list(query.order_by('-track_popularity'))


def find_album_by_name(album):
    query = Album.objects.filter(album_name__contains=album)
    resp = list(query)
    # Randomize to get different results each time
    random.shuffle(resp)
    # Return the id of up to 3 albums
    return {
        'albums': resp[:3]
    }


def find_track_by_name(track):

recommender/templates/base.html
{% load static %}
{% load pfp_exists %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
        {% block title %}{% endblock %}
    </title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>


    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.8.0"></script>

</head>


<!-- CSRF token added to htmx headers for htmx requests -->

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <div class='navbar fixed-top' style="display:flex;background-color:white;">
        <div class="nav-left" style="padding:4px;display:flex;gap:30px;justify-content:start;">
            <a class="navbar-brand" href='/'>
                <img src="{% static 'logo.svg' %}" alt="logo" style="height:35px;width:212px;padding:1px">
            </a>
            <div>
                <a href="{% url 'recommender:get_explore' %}" class="btn btn-link-custom">Explore</a>
            </div>

            <div>
                <a href="{% url 'recommender:get_playlists' %}" class="btn btn-link-custom">Playlists</a>
            </div>

            <div class="dropdown text-center">
                <button class="btn btn-link-custom dropdown-toggle" type="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Search
                </button>
                <ul class="dropdown-menu dropdown-menu-center">
                    <li><a href="{% url 'recommender:get_artist' %}" class="btn btn-link-custom">Artist</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a href="{% url 'recommender:get_album' %}" class="btn btn-link-custom">Album</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a href="{% url 'recommender:get_track' %}" class="btn btn-link-custom">Track</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a href="{% url 'recommender:get_user' %}" class="btn btn-link-custom">User</a></li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <a href="{% url 'recommender:get_history' %}" class="btn btn-link-custom">Search History</a>
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="nav-right" style="display:flex;gap:15px;justify-content:start;margin-right:25px">
            {% if request.user.is_authenticated %}
            <div>
                <a href="{% url 'recommender:get_myprofile' %}" class="btn btn-outline-custom"><img
                        src="{% get_static_prefix %}{{ user.username|pfp_exists }}.jpg"
                        class="rounded-circle card-img-top" border="1px"
                        style="object-fit:cover;height:22px;width:22px;margin-right:5px;margin-bottom:3px;">{{request.user.username}}</a>
            </div>
            <div>
                <a href="{% url 'recommender:logout_view' %}" class="btn btn-custom">Logout</a>
            </div>
            {% else %}
            <div>
                <a href="{% url 'recommender:get_signin' %}" class="btn btn-outline-custom">Sign In</a>
            </div>
            <div>
                <a href="{% url 'recommender:get_registration' %}" class="btn btn-custom">Register</a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="container" style="margin-top:100px">
        {% block content %}
        {% endblock %}
    </div>
    </head>
</body>

</html>

recommender/templates/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
<script src="{% static 'js/bootstrap.min.js' %}"></script>