music/urls.py
from django.contrib import admin
from django.urls import path, include
from recommender import views
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='recommender/')),
    path('recommender/', include('recommender.urls')),
    path('social/', include('social_django.urls')),
    path('accounts/profile/', views.post_sign_in, name='post_sign_in'),
]

recommender/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'recommender'

urlpatterns = [
    path('', views.get_home, name='get_home'),
    path('home/', views.get_home, name='get_home'),
    path('explore/', views.get_explore, name='get_explore'),

    path('signin/', views.get_signin, name='get_signin'),
    path('registration/', views.get_registration, name='get_registration'),
    path('logout/',views.logout_view,name="logout_view"),
    path('logout_view/', views.logout_view, name='logout_view'),

    path('profile/<str:user_name>', views.get_profile, name='get_profile'),

    path('myprofile/', views.get_myprofile,name='get_myprofile'),
    path('myprofile/profile_pic/', views.update_profile_picture, name='update_profile_picture'),
    path('myprofile/edit_bio/', views.update_bio, name='edit_bio'),
    path('myprofile/update_bio/', views.update_bio, name='update_bio'),
    path('myprofile/settings/',views.get_settings,name="get_settings"),
    path('myprofile/update_settings/',views.update_settings,name="update_settings"),
    path('myprofile/password/', views.change_password, name="change_password"),
    
    path('history/', views.get_history, name='get_history'),

    path('artist/', views.get_artist, name='get_artist'),
    path('album/', views.get_album, name='get_album'),
    path('track/', views.get_track, name='get_track'),
    path('user/', views.get_user, name='get_user'),
    
    path('playlist/', views.get_playlists, name='get_playlists'),
    path('playlist/<int:playlist_num>/', views.playlist_view, name='playlist_view'),
    path('playlist/<str:user_name>/', views.get_user_playlists, name='get_user_playlists'),
    path('playlist/create/<str:user_name>/', views.create_playlist, name='create_playlist'),
    path('playlist/<int:playlist_num>/add_song_update', views.add_song_update, name='add_song_update'),
    path('playlist/<int:playlist_num>/add_song_update/<str:song_id>', views.playlist_append, name="playlist_append"),
    path('playlist/<int:playlist_num>/remove_song_update/<str:song_id>', views.remove_song, name="remove_song"),

    path('following/<str:user_name>', views.get_following, name='get_following'),
    path('follow/<str:friend_name>', views.following_list_append, name='add_friend'),
    path('unfollow/<str:friend_name>', views.following_list_remove, name='remove_friend'),
    path('followers/<str:user_name>', views.get_followers, name='get_followers'),

    path('dislikes/', views.get_dislikes, name= 'get_dislikes'),
    path('dislikes/<str:user_name>', views.get_dislikes, name= 'get_dislikes'),
    path('dislike/song/<str:user_name>/<str:track_id>', views.dislike_song, name='dislike_song'),
    path('undislike/song/<str:user_name>/<str:track_id>/', views.undislike_song, name='undislike_song'),
    path('dislike/album/<str:user_name>/<str:album_id>', views.dislike_album, name='dislike_album'),
    path('undislike/album/<str:user_name>/<str:album_id>/', views.undislike_album, name='undislike_album'),
    path('dislike/artist/<str:user_name>/<str:artist_id>', views.dislike_artist, name='dislike_artist'),
    path('undislike/artist/<str:user_name>/<str:artist_id>/', views.undislike_artist, name='undislike_artist'),
    path('dislike/playlist/<str:user_name>/<str:playlist_id>', views.dislike_playlist, name='dislike_playlist'),
    path('undislike/playlist/<str:user_name>/<str:playlist_id>/', views.undislike_playlist, name='undislike_playlist'),
    
    path('album/<str:album_id>/', views.view_album, name="view_album"),
    path('artist/<str:artist_name>/', views.view_artist, name="view_artist"),
]
 

recommender/views.py
import random
from pickle import GET
from .models import *
from .forms import RegisterForm, SigninForm, UpdateSettingsForm, UpdatePasswordForm, SearchForm, PlaylistForm, ProfilePictureForm, BioForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect
from collections import Counter


def get_home(request):
    MAX_LENGTH = 3
    dislikes = Dislikes.objects.all()

    getDislikedSongs = dislikes.values_list('tracks', flat=True)
    dislikedSongs = []
    songCount = Counter(getDislikedSongs)
    topSongs = songCount.most_common(3)
    for song in topSongs:
        if song and len(dislikedSongs) < MAX_LENGTH:
            if song not in dislikedSongs:
                dislikedSongs.append(Musicdata.objects.get(id=song[0]))
                
    getDislikedAlbums = dislikes.values_list('albums', flat=True)
    dislikedAlbums = []
    albumCount = Counter(getDislikedAlbums)
    topAlbums = albumCount.most_common(3)
    for album in topAlbums:
        if album and len(dislikedAlbums) < MAX_LENGTH:
            if album not in dislikedAlbums:
                dislikedAlbums.append(Album.objects.get(album_id=album[0]))


    getDislikedPlaylists = dislikes.values_list('playlists', flat=True)
    dislikedPlaylists = []
    playlistCount = Counter(getDislikedPlaylists)
    topPlaylists = playlistCount.most_common(3)
    for playlist in topPlaylists:
        if playlist and len(dislikedPlaylists) < MAX_LENGTH:
            if playlist not in dislikedPlaylists:
                dislikedPlaylists.append(
                    Playlist.objects.get(playlist_id=str(int(playlist[0])-1)))

    if request.user.is_authenticated:

        owner = User.objects.get(username=request.user.username)
        userPlaylists = Playlist.objects.filter(playlist_owner=owner)
        Userdislikes = Dislikes.objects.filter(user=owner)

        getDislikedSongs = Userdislikes.values_list('tracks', flat=True)
        UserdislikedSongs = []
        for track in getDislikedSongs:
            if track:
                UserdislikedSongs.append(Musicdata.objects.get(id=track))

        getDislikedAlbums = Userdislikes.values_list('albums', flat=True)
        UserdislikedAlbums = []
        for album in getDislikedAlbums:
            if album:
                UserdislikedAlbums.append(Album.objects.get(album_id=album))

        getDislikedPlaylists = Userdislikes.values_list('playlists', flat=True)
        UserdislikedPlaylists = []
        for p in getDislikedPlaylists:
            if p:
                UserdislikedPlaylists.append(
                    Playlist.objects.get(playlist_id=str(int(p)-1)))
    else:  
        userPlaylists = []
        UserdislikedSongs = []
        UserdislikedAlbums = []
        UserdislikedPlaylists = []

    args = {
        'playlists': userPlaylists,
        'TopdislikedSongs': dislikedSongs,
        'TopdislikedAlbums': dislikedAlbums,
        'TopdislikedPlaylists': dislikedPlaylists,
        'dislikedSongs': UserdislikedSongs,
        'dislikedAlbums': UserdislikedAlbums,
        'dislikedPlaylists': UserdislikedPlaylists,
    }

    return render(request, "recommender/home.html", args)


def get_explore(request):
    songs = Musicdata.objects.all()
    sResp = list(songs)
    random.shuffle(sResp)
    albums = Album.objects.all()
    alResp = list(albums)
    random.shuffle(alResp)
    playlists = Playlist.objects.all()
    pResp = list(playlists)
    random.shuffle(pResp)
    artists = Artist.objects.all()
    arResp = list(artists)
    random.shuffle(arResp)
    userResp = User.objects.all()
    uResp = list(userResp)
    random.shuffle(uResp)

    if request.user.is_authenticated:

        following = FriendsList.objects.filter(user=request.user).values_list('friends')
        followingList = []
        for f in following:
            followingList.append(User.objects.get(id=f[0]))

        owner = User.objects.get(username=request.user.username)
        userPlaylists = Playlist.objects.filter(playlist_owner=owner)
        dislikes = Dislikes.objects.filter(user=owner)

        getDislikedSongs = dislikes.values_list('tracks', flat=True)
        dislikedSongs = []
        for track in getDislikedSongs:
            if track:
                dislikedSongs.append(Musicdata.objects.get(id=track))

        getDislikedArtists = dislikes.values_list('artists', flat=True)
        dislikedArtists = []
        for artist in getDislikedArtists:
            if artist:
                dislikedArtists.append(Artist.objects.get(artist_id=artist))

        getDislikedAlbums = dislikes.values_list('albums', flat=True)
        dislikedAlbums = []
        for album in getDislikedAlbums:
            if album:
                dislikedAlbums.append(Album.objects.get(album_id=album))

        getDislikedPlaylists = dislikes.values_list('playlists', flat=True)
        dislikedPlaylists = []
        for p in getDislikedPlaylists:
            if p:
                dislikedPlaylists.append(
                    Playlist.objects.get(playlist_id=str(int(p)-1)))

        friends = FriendsList.objects.filter(user=request.user).values_list('friends')
        friendsList = list(friends)
        friendsDislikeSongList = []
        friendsDislikeAlbumList = []
        friendsDislikePlaylistList = []
        if friendsList:
            for friend in friendsList:
                friendsDislikes = Dislikes.objects.filter(user=friend)
                getFriendsDislikedSongs = friendsDislikes.values_list('tracks',flat=True)
                getFriendsDislikedAlbums = friendsDislikes.values_list('albums',flat=True)
                getFriendsDislikedPlaylists = friendsDislikes.values_list('playlists',flat=True)
                for track in getFriendsDislikedSongs:
                    if track:
                        friendsDislikeSongList.append(Musicdata.objects.get(id=track))
                for album in getFriendsDislikedAlbums:
                    if album:
                        friendsDislikeAlbumList.append(Album.objects.get(album_id=album))
                for playlist in getFriendsDislikedPlaylists:
                    if playlist:
                        friendsDislikePlaylistList.append(Playlist.objects.get(playlist_id=str(int(playlist) - 1)))

            friendsDislikeSongList = friendsDislikeSongList[:3]
            friendsDislikeAlbumList = friendsDislikeAlbumList[:3]
            friendsDislikePlaylistList = friendsDislikePlaylistList[:3]

            if len(friendsDislikeSongList) < 3:
                for _ in range(3 - len(friendsDislikeSongList)):
                    while True:
                        currSong = random.choice(list(Musicdata.objects.all()))
                        if currSong not in friendsDislikeSongList:
                            friendsDislikeSongList.append(currSong)
                            break

            if len(friendsDislikeAlbumList) < 3:
                for _ in range(3 - len(friendsDislikeAlbumList)):
                    while True:
                        currAlbum = random.choice(list(Album.objects.all()))
                        if currAlbum not in friendsDislikeAlbumList:
                            friendsDislikeAlbumList.append(currAlbum)
                            break
                    
            if len(friendsDislikePlaylistList) < 3:
                for _ in range(3 - len(friendsDislikePlaylistList)):
                    while True:
                        currPlaylist = random.choice(list(Playlist.objects.all()))
                        if currPlaylist not in friendsDislikePlaylistList:
                            friendsDislikePlaylistList.append(currPlaylist)
                            break

            random.shuffle(friendsDislikeSongList)
            random.shuffle(friendsDislikeAlbumList)
            random.shuffle(friendsDislikePlaylistList)

    else:
        userPlaylists = []
        dislikedSongs = []
        dislikedAlbums = []
        dislikedArtists = []
        dislikedPlaylists = []
        friendsDislikeSongList = []
        friendsDislikeAlbumList = []
        friendsDislikePlaylistList = []
        followingList = []

    args = {
        'songs': sResp[:3],
        'albums': alResp[:3],
        'recPlaylists': pResp[:3],
        'artists': arResp[:3],
        'users': uResp[:10],
        'playlists': userPlaylists,
        'dislikedSongs': dislikedSongs,
        'dislikedAlbums': dislikedAlbums,
        'dislikedArtists': dislikedArtists,
        'dislikedPlaylists': dislikedPlaylists,
        'friendsDislikeSongList': friendsDislikeSongList,
        'friendsDislikeAlbumList': friendsDislikeAlbumList,
        'friendsDislikePlaylistList': friendsDislikePlaylistList,
        'following': followingList,
    }
    return render(request, "recommender/explore.html", args)


def find_albums(artist, from_year=None, to_year=None):
    query = Musicdata.objects.filter(track_artist__contains=artist)
    if from_year is not None:
        query = query.filter(track_album_release_date__gte=from_year)
    if to_year is not None:
        query = query.filter(track_album_release_date__lte=to_year)
    # return list(query.order_by('-track_popularity').values('track_id'))
    return list(query.order_by('-track_popularity'))


def find_album_by_name(album):
    query = Album.objects.filter(album_name__contains=album)
    resp = list(query)
    # Randomize to get different results each time
    random.shuffle(resp)
    # Return the id of up to 3 albums
    return {
        'albums': resp[:3]
    }


def find_track_by_name(track):

recommender/templates/recommender/add_song.html
{% extends 'base.html' %}

{% block title %} Add Song by Search {% endblock %}

{% block content %}

<form method='post' class="form" action="{% url 'recommender:add_song' playlist_num %}">
    {% csrf_token %}
    <br>
    <center>
        <h2>Add Song by Search</h2>
            <p>Song Name: {{ form.song_name }}</p>
            <p>Artist Name: {{ form.song_artist }}</p>
            <button class="btn btn-primary btn-lg"  type="submit">
                Search
            </button>

</center>
</form>
<br>


{% if songs %}
<table class="table">
<tbody>
<tr>

{% for song in songs %}

<td>
<iframe src="https://open.spotify.com/embed/track/{{ song.track_id }}" width="300" height="380" 
frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
<button type="button">Add</button>
</td>

{% endfor %}

</tr>
</tbody>
</table>

{% endif %}

{% endblock %}

recommender/templates/recommender/add_song_update.html
{% extends 'base.html' %}

{% block title %} Add Songs by Search {% endblock %}

{% block content %}

    <a class="btn btn-outline-custom" href="{% url "recommender:playlist_view" playlist_num %}">&lt; Back to Playlist</a>
    <br>
    <center>
        <h2>Add Songs by Search</h2>
    
        <br>
        <input class="form-text col-8" style="margin-bottom:25px" type="text"
        name="song" hx-get="{% url 'recommender:add_song_update' playlist_num %}" 
        hx-trigger="keyup" hx-target="#search-results">
        </input>
        <br>
        
        <div id="search-results">
        </div>
    </center>
    </br>

{% endblock %}

recommender/templates/recommender/artist_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{artist.artist_name}} {% endblock %}

{% block content %}

<div class="header" style="display:flex;flex-direction:row;justify-content:space-between;">
    <div class="left-header">
        <h3>{{ artist.artist_name }}</h3>
    </div>
    {% if request.user.is_authenticated %}
    <div class="right-header" style="display:flex;flex-direction:row;justify-content:right;gap:15px">
        {% if artist in dislikedArtist %}
        <a href="{% url 'recommender:undislike_artist' user.username artist.artist_id %}" class="btn btn-link-custom">
        <img src="{% static 'dislike-filled.svg' %}" alt="Un-dislike" title="Un-dislike" style="height:40px;width:40px;"></a>
        {% else %}
        <a href="{% url 'recommender:dislike_artist' user.username artist.artist_id %}" class="btn btn-link-custom">
        <img src="{% static 'dislike.svg' %}" alt="Dislike" title="Dislike" style="height:40px;width:40px;"></a> 
        {% endif %}
    </div>
    {% endif %}
</div>

<hr/>

<ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:45px">
    {% for album in artist_albums.all%}
        {% include "recommender/albumcards.html" %}
    {% endfor %}
</ol>

{% endblock %}

recommender/templates/recommender/artistcards.html
{% load static %}           
<li style="width:30%;">
      <div class="card">
        <center class="card-body">
          {% if artist.artist_name %}<h5 class="card-title">{{ artist.artist_name }}</h5>{% endif %}
        
        
            {% for song in artist.artist_tracks.all|slice:":3" %}
                <iframe src="https://open.spotify.com/embed/track/{{ song.track_id }}" width="100%" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media" style="margin-bottom:15px;"></iframe>
            {% endfor %}

                <div style="display:flex;flex-direction:column;gap:5%;justify-content:center;">
                    <div style="margin-top:12px;"><a href={% url 'recommender:view_artist' artist.artist_name %} class="btn btn-outline-custom" style="width:60%">{{artist.artist_name}}</a></div>

                    {% if request.user.is_authenticated %}
                    {% if artist in dislikedArtists %}
                        <a href="{% url 'recommender:undislike_artist' user.username artist.artist_id %}" class="btn btn-link-custom">
                        <img src="{% static 'dislike-filled.svg' %}" alt="Un-dislike" title="Un-dislike" style="height:40px;width:40px;"></a>
                    {% else %}
                        <a href="{% url 'recommender:dislike_artist' user.username artist.artist_id %}" class="btn btn-link-custom">
                        <img src="{% static 'dislike.svg' %}" alt="Dislike" title="Dislike" style="height:40px;width:40px;"></a> 
                    {% endif %}
                    {% endif %}
                </div> 

              </center>
          </div>
  </li>

recommender/templates/recommender/edit_settings.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Profile {% endblock %}

{% block content %}

<div class="card" style="width: 100%; margin-bottom: 20px">
    <div class="card-body">
      <h5 class="card-title" style="margin-bottom:20px">Edit Your Details</h5>
        <form method='post' class="form" style="margin-left:50px;margin-right:50px">

          {% csrf_token %}

          <div class="form-floating mb-3">
            {{form.first_name}}
            <label for="floatingInput">First Name</label>
          </div>

          <div class="form-floating mb-3">
            {{form.last_name}}
            <label for="floatingInput">Last Name</label>
          </div>

          <div class="form-floating mb-3">
            {{form.username}}
            <label for="floatingInput">Username</label>
          </div>

          <div class="form-floating mb-3">
            {{form.email}}
            <label for="floatingInput">Email</label>
          </div>
          
          
          <div style="text-align: right">
              <button type="submit" class="btn btn-custom">Save Changes</button>
          </div>
        </form>
    </div>
    <br>
</div>

{% endblock %}

recommender/templates/recommender/explore.html
{% extends 'base.html' %}
{% load static %}
{% load pfp_exists %}

{% block title %} Explore {% endblock %}

{% block content %}
<div class='nav'>
  <div class="row" style="margin-top: -30px;">
    <div class="col-md-4" id="left">
      {% if users %}
      {% for user in users %}
      <div class="card" style="width: 100%; margin-bottom: 20px">
        <div class="row">
          <center style="padding:30px">
            <img src="{% get_static_prefix %}{{ user.username|pfp_exists }}.jpg" class="rounded-circle card-img-top"
              border="1px" style="object-fit: cover; height:225px;width:225px;">
          </center>
          <div class="card-body" style="text-align: center;">
            <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
            <h6 class="card-subtitle" style="margin-bottom: 20px">@{{ user }}</h6>
            <a href={% url 'recommender:get_profile' user %} class="btn btn-outline-custom">View Profile</a>
            {% if request.user.is_authenticated %}
            {% if user in following %}
            <a href={% url "recommender:remove_friend" user %} class="btn btn-custom" style="margin-left: 10px">Unfollow</a>
            {% else %}
            <a href={% url "recommender:add_friend" user %} class="btn btn-custom" style="margin-left: 10px">Follow</a>
            {% endif %}
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}
    </div>

    <div class="col-md-8" id="right">
      <div class="card" style="width: 100%; margin-bottom: 20px">
        <div class="card-body">
          <h5 class="card-title">"Recomended" Songs</h5>
          <h6 class="card-subtitle mb-2 text-muted">Songs you might dislike</h6>
          {% if friendsDislikeSongList %}
          <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:25px">
            {% for song in friendsDislikeSongList %}
            {% include "recommender/songcards.html" %}
            {% endfor %}
          </ol>
          {% else %}
          <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:25px">
            {% for song in songs %}
            {% include "recommender/songcards.html" %}
            {% endfor %}
          </ol>
          {% endif %}
        </div>
      </div>

      <div class="card" style="width: 100%; margin-bottom: 20px">
        <div class="card-body">
          <h5 class="card-title">"Recomended" Albums</h5>
          <h6 class="card-subtitle mb-2 text-muted">Albums you might dislike</h6>
          {% if friendsDislikeAlbumList %}
          <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:25px">
            {% for album in friendsDislikeAlbumList %}
            {% include "recommender/albumcards.html" %}
            {% endfor %}
          </ol>
          {% elif albums %}
          <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:25px">
            {% for album in albums %}
            {% include "recommender/albumcards.html" %}
            {% endfor %}
          </ol>
          {% endif %}
        </div>
      </div>

      <div class="card" style="width: 100%; margin-bottom: 20px">
        <div class="card-body">
          <h5 class="card-title">"Recomended" Playlists</h5>
          <h6 class="card-subtitle mb-2 text-muted">Playlists you might dislike</h6>
          {% if friendsDislikePlaylistList %}
          <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:25px">
            {% for playlist in friendsDislikePlaylistList %}
            {% include "recommender/playlistcards.html" %}
            {% endfor %}
          </ol>
          {% elif recPlaylists %}
          <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:25px">
            {% for playlist in recPlaylists %}
            {% include "recommender/playlistcards.html" %}
            {% endfor %}
          </ol>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

recommender/templates/recommender/profile.html
{% extends 'base.html' %}
{% load static %}
{% load pfp_exists %}

{% block title %} {{profile_user.username}}'s Profile {% endblock %}

{% block content %}


          
<div class="card" style="width: 100%; margin-bottom: 20px">  
  <div class="card-body">
    <div style="display:flex;gap:20px;justify-content:left">
        <img src="{% get_static_prefix %}{{ profile_user.username|pfp_exists }}.jpg" class="rounded-circle card-img-top" border="1px" class="rounded-circle" border="1px" style="width: 80px; height: 80px; object-fit: cover">
    <div style="display:flex;flex-direction:column;justify-content:center">
      <h5 class="card-title">{{profile_user.first_name}} {{profile_user.last_name}}</h5>
      <h6 class="card-text">@{{profile_user}}</h6>
    </div>
  </div>
  {% if bio %}
    <div class="card-text text-muted" style="margin:15px">{{bio}}</div>
  {% endif %}
  <div class="card-body" style="text-align: right;">
    {% if followers %}
    <a href="{% url "recommender:get_followers" profile_user %}" class="btn btn-outline-custom" style="margin-right: 10px">Followers: {{countfollowers|length}}</a>
    {% endif %}
    {% if following %}
    <a href="{% url "recommender:get_following" profile_user %}" class="btn btn-outline-custom" style="margin-right: 10px">Following: {{countfollowing|length}}</a>
    {% endif %}
    {% if profile_user in userFollowing %}
    <a href={% url "recommender:remove_friend" profile_user%} class="btn btn-custom">Unfollow</a>
    {% else %}
    <a href={% url "recommender:add_friend" profile_user%} class="btn btn-custom">Follow</a>
    {% endif %}
  </div>
</div>
</div>

{% if playlists %}
<div class="card" style="width: 100%; margin-bottom: 20px">
  <div class="card-body">
      <h5 class="card-title">@{{profile_user}}'s Playlists</h5>
        <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:45px">
            {% for playlist in playlists %}
              {% include "recommender/playlistcards.html" %}
            {% endfor %}
        </ol>
  </div>
</div>
{% endif %}

{% if followers %}
<div class="card" style="width: 100%; margin-bottom: 20px">
  <div class="card-body">
      <h5 class="card-title">A few of @{{profile_user}}'s followers</h5>
        <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:45px">
            {% for friend in followers %}
            {% if friend %}
            <div class="card" style="width: 30%; margin-bottom: 20px">
                <div class="row">
                <center>    
                    <img src="{% get_static_prefix %}{{ friend.username|pfp_exists }}.jpg" class="rounded-circle card-img-top" border="1px" style="object-fit: cover; height: 250px; width: 250px; margin-top: 25px">
                </center>
                <div class="card-body" style="text-align: center;">
                  <h5 class="card-title">{{ friend.first_name }} {{ friend.last_name }}</h5>
                  <h6 class="card-subtitle" style="margin-bottom: 20px">@{{ friend }}</h6>
                  <a href={% url 'recommender:get_profile' friend %} class="btn btn-outline-custom">View Profile</a>
                </div>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </ol>
  </div>
</div>
{% endif %}

{% if following %}
<div class="card" style="width: 100%; margin-bottom: 20px">
  <div class="card-body">
      <h5 class="card-title">A few of @{{profile_user}}'s following</h5>
        <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:45px">
            {% for friend in following %}
            {% if friend %}
            <div class="card" style="width: 30%; margin-bottom: 20px">
                <div class="row">
                <center>    
                    <img src="{% get_static_prefix %}{{ friend.username|pfp_exists }}.jpg" class="rounded-circle card-img-top" border="1px" style="object-fit: cover; height: 250px; width: 250px; margin-top: 25px">
                </center>
                <div class="card-body" style="text-align: center;">
                  <h5 class="card-title">{{ friend.first_name }} {{ friend.last_name }}</h5>
                  <h6 class="card-subtitle" style="margin-bottom: 20px">@{{ friend }}</h6>
                  <a href={% url 'recommender:get_profile' friend %} class="btn btn-outline-custom">View Profile</a>
                </div>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </ol>
  </div>
</div>
{% endif %}

{% endblock %}

recommender/templates/recommender/results3.html
{% if songs %}
    {% for song in songs %}
    <ol style="display:flex;flex-direction:row;flex-wrap:wrap;list-style:none;gap:50px 30px;">
        <div class="card">
            <div class="card-body"> 
                <td>
                    <iframe src="https://open.spotify.com/embed/track/{{ song }}" width="300" height="380" 
                    frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                </td>
                <div class = "text-center">
                    <a class="btn btn-custom" href={% url "recommender:playlist_append" playlist_num song %}>Add Song</a>
                </div>
            </div>
        </div>
    <ol>
    {% endfor %}
{% endif %}

recommender/templates/recommender/track.html
{% extends 'base.html' %}

{% block title %} Track Search {% endblock %}

{% block content %}

    <br>
    <center>
        <h2>Track Search</h2>
    
        <br>
        <input class="form-text col-8" style="margin-bottom:25px" type="text"
        name="track" hx-get="{% url 'recommender:get_track' %}" 
        hx-trigger="keyup" hx-target="#search-results">
        </input>
        <br>
        
        <div id="search-results">
        </div>
    </center>

{% endblock %}